#!/bin/bash

# Note:
# If you see some functions using "_helper_" functions, they are defined
# in $HOME/dotfiles/helpers.sh
#
# They are reusable tools that you might not want to wade through every
# time you open your bash_functions script.

# ***********
# **  SSH  **
# ***********

# sshcd - ssh to a host, retaining your current directory
#   Usage:   sshcd hostname [optional command to run]
#   Example: sshcd lfe-console ls -l
sshcd() {
    host=$1;
    shift;
    command="$*";
    ssh -t "$host" "
        cd '${PWD}'
        echo 'Current working directory: $PWD'
        ${command}
        bash
    ";
}

# ***********
# **  GIT  **
# ***********

# git_setup_fork: clone your fork, add the upstream repo as a remote
#   Usage:   get_setup_fork org/repo
#   Example: git_setup_fork pcdshub/pcdsdevices
#
# Configure the defaults with the following env variables:
#   - GITHUB_USERNAME
#   - GITHUB_UPSTREAM
#   - GITHUB_ORIGIN
git_setup_fork() {
  usage="git_setup_fork org/repo"
  if [ -z "${1}" ]; then
    echo "${usage}"
    return
  fi
  REPO=`basename "${1}"`
  UPSTREAM=`dirname "${1}"`
  git clone --origin "${GITHUB_ORIGIN:-origin}" "git@github.com:${GITHUB_USERNAME:-${USER}}/${REPO}.git"
  git -C "${REPO}" remote add "${GITHUB_UPSTREAM:-upstream}" "git@github.com:${UPSTREAM}/${REPO}.git"
}

# git_sync_upstream: pull changes from upstream master, push to your master
#   Usage: git_sync_upstream
#
# Configure the defaults with the following env variables:
#   - GITHUB_UPSTREAM
#   - GITHUB_ORIGIN
#   - GITHUB_MASTER
git_sync_upstream() {
  git checkout "${GITHUB_MASTER:-master}"
  git fetch "${GITHUB_UPSTREAM:-upstream}"
  git pull "${GITHUB_UPSTREAM:-upstream}" "${GITHUB_MASTER:-master}"
  git push "${GITHUB_ORIGIN:-origin}" "${GITHUB_MASTER:-master}"
}


# **********
# ** IOCs **
# **********


# Watch a log file from a given IOC.
#  Usage: ioclog (iocname)
#  Example: ioclog ioc-xpp-gige-las01
#  Example: ioclog ioc-xpp-*-las01
ioclog() {
    # shellcheck disable=SC2086 # allow for globbing of IOC names
    tail -n 50 -f /cds/data/iocData/$1/iocInfo/ioc.log
}

# Find a currently-deployed IOC with a bit more details:
#  Usage: which_ioc [iocname]
#  Example: which_ioc
#  Example: which_ioc ioc-xpp-gige-las01
#  Example: which_ioc ioc-xpp-.*-las01
#  Full version is available in a table here:
#       https://confluence.slac.stanford.edu/display/PCDS/EPICS+IOCs+Deployed+in+IOC+Manager
#  Note: this is derived from "whatrecord iocmanager-loader" and is run on a
#        personal cron job.
which_ioc() {
    local to_find=$1
    local fzf
    fzf=$(_helper_find_fzf)
    if [ -z "$fzf" ]; then
        grep -i -e "$to_find" "$_ALL_IOCS_TEXT"
    else
        $fzf +m -q "$to_find" < "$_ALL_IOCS_TEXT"
    fi
}

# Find a currently-deployed IOC with a bit more details, in JSON:
#  Usage: which_ioc_json [iocname]
#  Example: which_ioc_json
#  Example: which_ioc_json ioc-xpp-gige-las01
#  Example: which_ioc_json ioc-xpp-.*-las01
which_ioc_json() {
    local to_find=$1
    local ioc_name
    ioc_name=$( which_ioc "$to_find" | cut -d "|" -f 2 | sed -e "s/\s*//g" )
    _helper_get_ioc_info_json "$ioc_name"
}

# Go to an IOC data directory (with fuzzy searching).
#  Usage: cdiocdata [query]
#  Example: cdiocdata
#  Example: cdiocdata ioc-xcs
cdiocdata() {
    _helper_cd_under /cds/data/iocData "$@"
}

# Go to an IOC startup script directory (with fuzzy searching).
#  Usage: cdioc [iocname]
#  Example: cdioc
#  Example: cdioc ioc-xcs
#  For each example, user input is required to pick the IOC.
cdioc() {
    local ioc_path
    local ioc_startup
    local jq
    ioc_info_json=$(which_ioc_json "$@")
    echo "$ioc_info_json"

    jq=$(_helper_find_jq)

    if [ -z "$jq" ]; then
        return;
    fi

    ioc_startup=$(echo "$ioc_info_json" | $jq -r ".script" )
    ioc_path=$(dirname "$ioc_startup")

    if [ -d "$ioc_path" ]; then
        _helper_cd_verbose "$ioc_path"
    else
        echo "$ioc_path does not exist"
    fi
}

# List all currently-deployed IOC with a bit more details.
#  Usage: list_all_iocs
list_all_iocs() {
    less /cds/data/iocData/.all_iocs/iocs.txt
}


# *****************************
# ** Python and hutch-python **
# *****************************

# ipython_debug_entrypoint
#   Start an ipython debug session with your script, and get to the PDB prompt
#   only if it encounters an error.  This could be used, for example, with
#   typhos by way of "ipython_debug_entrypoint typhos ..typhos args.."
ipython_debug_entrypoint() {
    cmd=$(which "$1")
    shift
    if [ -n "$cmd" ]; then
        set -x
        ipython -i --pdb "$cmd" -- "$@"
        set +x
    fi
}

# cdhutchp - go to the per-hutch hutch-python configuration directory.
#   Usage: cdhutchp [hutch_name]
#   Example: cdhutchp rix
cdhutchp() {
    hutch=$(_helper_maybe_get_hutch "$1")
    [ "$hutch" == "unknown_hutch" ] && echo "Unknown hutch for $(hostname -s). Please specify a hutch." && return
    _helper_cd_verbose "/cds/group/pcds/pyps/apps/hutch-python/$hutch/"
}

# cdhutchp_logs - go to the per-hutch hutch-python log directory.
#   Usage: cdhutchp_logs (hutch_name)
#   Example: cdhutchp_logs rix
cdhutchp_logs() {
    hutch=$(_helper_maybe_get_hutch "$1")
    [ "$hutch" == "unknown_hutch" ] && echo "Unknown hutch for $(hostname -s). Please specify a hutch." && return
    log_path="/cds/group/pcds/pyps/apps/hutch-python/${hutch}/logs"
    current_year=$(date -u +"%Y_")
    current_month=$(date -u +"%Y_%m")
    date_path="${log_path}/${current_month}"
    if [ -d "$date_path" ]; then
        echo "$date_path"
        _helper_cd_verbose "$date_path"
    else
        echo "$log_path"
        # shellcheck disable=SC2164
        cd "$log_path" && ls -d "${current_year}"*
    fi
}

# cdhutchconfig - go to the per-hutch configuration directory.
#   Usage: cdhutchconfig (hutch_name)
#   Example: cdhutchconfig rix
cdhutchconfig() {
    hutch=$(_helper_maybe_get_hutch "$1")
    [ "$hutch" == "unknown_hutch" ] && echo "Unknown hutch for $(hostname -s). Please specify a hutch." && return
    _helper_cd_verbose "/cds/group/pcds/config/$hutch/"
}

# markdown_view - view GitHub-flavored markdown files in lynx
#  Usage: markdown_view filename.md
#  Example: markdown_view helpme.md
markdown_view() {
    markdown_file="$1"
    if [ -z "$markdown_file" ]; then
        echo "Usage: markdown_view filename.md"
        return
    fi

    pandoc="$_PCDS_CONDA_FOR_UTILS/bin/pandoc"
    lynx=$(command -v lynx 2>/dev/null)
    if [ -x "$lynx" ]; then
        echo "Opening $markdown_file with lynx..."
        exec "${pandoc}" --from gfm --to html "$markdown_file" | "$lynx" -stdin
    else
        less "$markdown_file"
    fi
}

# which_command - show all commands and where they come from.
#   Note that this can take a while to list everything.  Consider
#   using it with grep or fzf to find what you're looking for.
#  Usage: which_command
#  Example: which_command | fzf
which_command() {
    local cmd
    local location
    for cmd in $(compgen -c | sort | uniq); do
        location=$(which --skip-functions --skip-alias "$cmd" 2> /dev/null)
        if [ -n "$location" ]; then
            echo "$cmd ($location)"
        else
            echo "$cmd"
        fi
    done
}

# helpme
#   Usage: helpme
helpme() {
    # shellcheck disable=SC2154
    markdown_view "$dotfiles/helpme.md"
}

# ****************
# ** What now?  **
# ****************
#
# Add some more functions or modify the ones above to fit your needs.
# Also, use shellcheck to see that you're writing scripts with good syntax.
# The tool shellcheck is available in our pcds Python environment.
#
# For bash help, see https://tldp.org/LDP/Bash-Beginners-Guide/html/
