#!/bin/bash

# ****************
# ** Navigation **
# ****************

# Add color coding of files and directories:
alias ls='ls --color'

# "l" is short for "ls"
alias l='ls'

# "ll" is short for detailed file lists, with "ls -l":
alias ll='ls -lh'

# "lh" is short for detailed file lists with human-readable units:
alias lh='ls -Alh'

# "lt" lists files backwards in time since last edit
alias lt='ls -cltrh'

# Going up? :)
alias cd..='cd ..'
alias ..='cd ..'
alias ..1='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ..4='cd ../../../..'
alias ..5='cd ../../../../..'
alias ..6='cd ../../../../../..'
alias ..7='cd ../../../../../../..'
alias ..8='cd ../../../../../../../..'
alias ..9='cd ../../../../../../../../..'

# Open the most-recently-changed subdirectory of the current directory:
alias cdnewest='cd `ls -td --color=never */ | head -1`'

# Still there? Did you know ``cd -`` will take you back to the previous
# directory you were in?  Your current directory is $PWD and your previous one
# is $OLDPWD.

# ***********
# **  SSH  **
# ***********

# psb:
#   psbuild-rhel7 is one of the most common hosts you will use.
#   This shortcut ``psb`` will allow you to quickly go to that host while
#   retaining your current working directory.
alias psb='sshcd psbuild-rhel7'
alias psb5='sshcd psbuild-rhel5'
alias psd='sshcd psdev'
alias xppc='ssh -X xppopr@xpp-control'
alias xppd='ssh -X xppopr@xpp-daq'
alias mfxd='ssh -X mfxopr@mfx-daq'
alias tos3df='ssh -J espov@s3dflogin.slac.stanford.edu psana'

# *****************************
# ** Python and hutch-python **
# *****************************

# These are shortcuts for individual hutches to start hutch-python:
alias tmo3="hpy3 tmo"
alias txi3="hpy3 txi"
alias rix3="hpy3 rix"
alias xpp3="hpy3 xpp"
alias xcs3="hpy3 xcs"
alias mfx3="hpy3 mfx"
alias cxi3="hpy3 cxi"
alias mec3="hpy3 mec"

# Dir shrortcuts
alias anad='cd /cds/data/psdm/'
alias ffbd='cd /cds/data/drpsrcf/'
alias hpyd='cd /cds/group/pcds/pyps/apps/hutch-python/'
alias mydev='cd /cds/group/pcds/epics-dev/espov'
alias epd='cd /cds/group/pcds/epics/'
alias daqd='cd /cds/group/pcds/dist/pds'
alias daqlogs='/cds/group/pcds/pds/'
alias screens='cd /cds/group/pcds/epics-dev/screens/'
alias epicsd='cd /cds/group/pcds/epics/ioc/'
alias smd_release='cd /cds/group/psdm/sw/tools/smalldata_tools'


# Python 3 hutch python shortcuts
# hpy3
#   Quickly start a hutch-python session for a given hutch with ``hpy3 (hutchname)``
hpy3() {
    hutch="${1}"
    shift
    "/reg/g/pcds/pyps/apps/hutch-python/${hutch}/${hutch}python" "$@"
}


# ****************
# ** General    **
# ****************

# This allows for aliases to be passed through to sudo
alias sudo='sudo '

# Alias view so vimrc is properly read
alias view='vim -R'

# ************
# ** EPICS  **
# ************

# Want to get enum information from a PV? Use this:
alias cagetenum='caget -d 31'
alias cagetstring='caget -S'

# ****************
# ** What now?  **
# ****************
#
# Add some more aliases or modify the ones above to fit your needs.
# Also, use shellcheck to see that you're writing scripts with good syntax.
# The tool shellcheck is available in our pcds Python environment.
#
# For bash help, see https://tldp.org/LDP/Bash-Beginners-Guide/html/

# file alias
alias xppcnf='vim /cds/group/pcds/dist/pds/xpp/scripts/xpp.cnf'
alias mfxcnf='vim /cds/group/pcds/dist/pds/mfx/scripts/mfx.cnf'

# plg prog rdesktop
alias plcprog='rdesktop -g 1920x1200 -u ${USER} plcprog-console'
alias plcprog4k='rdesktop -g 3600x2000 -u ${USER} plcprog-console'

# Env aliases
alias pcdsconda='source pcds_conda'
alias anaenvpy2='source /reg/g/psdm/etc/psconda.sh'
alias anaenv='source /reg/g/psdm/etc/psconda.sh -py3'
alias xppenv='source /cds/group/pcds/pyps/apps/hutch-python/xpp/xppenv'
alias myconda='source /cds/home/e/espov/miniconda3/etc/profile.d/conda.sh'
alias ami2env='source /cds/group/pcds/dist/pds/ami2-devel/setup_env_lcls1.sh'

# Path alias
alias add_pwd_to_python='export PYTHONPATH=$PWD'

# Custom commands aliases
alias myiftop='sudo iftop -m 1G'
